### ISSUE TITLE
Front End has a register new user page and a login page. They do not have to be functional, but the HTML for the page is being served.

### ISSUE THREAD

**Issue by fahadfardeen** [Devpat1996/IT490#2]

**Comment by rrd32** [comment]
<h2>Login</h2>
<form method="post">
<div class="form-group">
<label for="email">Email Address</label>
<input type="email" name="email" class="form-control" id="email" placeholder="Enter email">
</div>
<div class="form-group">
<label for="password">Password</label>
<input type="password" name="password" class="form-control" id="password" placeholder="Password">
</div>
<button type="submit" class="btn btn-primary">Submit</button>
</form>
Don't have an account? <a href="/register">Register here!</a>
`from flask import Flask, render_template
app = Flask(__name__)

@app.route('/')
def hello_world():
	return 'Hello world from Fahad! in a docker container'
    
@app.route('/login')
def login():
	return render_template('login.html');
   	
if __name__== '__main__':
	app.run(debug=True, host='0.0.0.0')


Done.
