### ISSUE TITLE
Documentation is developed that describes how to use the RabbitMQ management interface to check to see if queues are being created. The documentation is in the form of a README file in any GitHub supported format within the messaging directory.

### ISSUE THREAD

**Issue by fahadfardeen** [Devpat1996/IT490#4]

**Comment by Devpat1996** [comment]
How to use RabbitMQ Management
What do I need in docker-compose.yml?
... messsaging: image: 'rabbitmq: 3.8.8-mangament' ports: - 15672:15672 ...

You would have to specify that you are using the management version and you need to forward port 15672.

How do I get to the web-interface?
You can get to the web interface by going to http://localhost:15672

What does it show?
In the Queues table under "All queues" it will show you any queues that you have made.

If you navigate to connections tab, you would be able to see everyone who is connected to this instance.





---> The README.md file has been added to the messaging folder. This file consists of a brief explanation on how RabbitMQ functions. Above is the example of the Markdown used in Notepad ++.
